apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: web-image-automation
  namespace: flux-system
spec:
  checkout:
    gitRepositoryRef:
      name: k8s-demo
  interval: 1m
  update:
    strategy: Setters
  commit:
    authorName: fluxcdbot
    authorEmail: fluxcdbot@example.com
  git:
    push:
      branch: main
  path: ./kustomize-lab/base
