apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: fluximages.azurecr.io/nginx:1.27.1 # {"$imagepolicy": "flux-system:web-policy"}
          ports:
            - containerPort: 80